/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visão;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro Cavudissa
 */
public class CadastroTurmas1 extends javax.swing.JFrame {

    /**
     * Creates new form CadastroTurmas
     */
    public CadastroTurmas1() {
        initComponents();
        actualizartabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdesignacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jcapacidade = new javax.swing.JSpinner();
        Bsalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Capacidade de Alocação");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, 22));

        jLabel3.setText("Designação");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 90, 22));

        txtdesignacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesignacaoActionPerformed(evt);
            }
        });
        jPanel1.add(txtdesignacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 121, -1));

        jLabel2.setText("Salas a Serem Alocadas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));
        jPanel1.add(Jcapacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 100, -1));

        Bsalvar.setText("Salvar");
        Bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalvarActionPerformed(evt);
            }
        });
        jPanel1.add(Bsalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sala", "Capacidade"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 330, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void actualizartabela(){
        try {
            DefaultTableModel actualiza=(DefaultTableModel) Tabela.getModel();
            BufferedReader ler=new BufferedReader(new FileReader("CadastroTurmas.txt"));
            String linha;
            actualiza.setRowCount(0);
            while((linha=ler.readLine())!=null){
            String[] partir=linha.split(";");
            actualiza.addRow(partir);
            }
        } catch (Exception e) {
        }
    }
    private void txtdesignacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesignacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesignacaoActionPerformed

    private void BsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalvarActionPerformed
        // TODO add your handling code here:
         try{
            BufferedWriter conexao;
            String nome,capacidade;
         
        nome=txtdesignacao.getText().toString().trim();
       // nif=txtnif.getText();
      capacidade=Jcapacidade.getValue().toString();
       if(nome == null || capacidade==null ){
            JOptionPane.showMessageDialog(rootPane,"Todos os campos devem ser preenchidos ou selecionados");
          } else {
               conexao=new BufferedWriter(new FileWriter("CadastroTurmas.txt", true));
            
             conexao.write(nome+";"+capacidade+";\n");
             JOptionPane.showMessageDialog(rootPane,"Dados salvos com sucesso");
              conexao.close();
              actualizartabela();
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu um ERRO");
        }
    }//GEN-LAST:event_BsalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroTurmas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroTurmas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsalvar;
    private javax.swing.JSpinner Jcapacidade;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtdesignacao;
    // End of variables declaration//GEN-END:variables
}
