/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visão;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Cavudissa
 */
public class CadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form CadastroAlunos
     */
    public CadastroAlunos() {
        initComponents();
        Add();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void Add(){
       

Csemestre.addActionListener(new ActionListener() {
    public void actionPerformed(ActionEvent evt) {
    }
});
    }
     
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnif = new javax.swing.JTextField();
        txtnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Cano = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jmasculino = new javax.swing.JRadioButton();
        Jfeminino = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        Csemestre = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nome Completo:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 66, -1, -1));

        jLabel2.setText("Gênero:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 121, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cadastro de Alunos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 22, -1, -1));

        jLabel4.setText("Data Nascimento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 154, -1, 22));
        jPanel1.add(txtnif, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 99, 121, -1));

        txtnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 66, 121, -1));

        jLabel5.setText("Ano a se inscrever:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 187, -1, -1));

        Cano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1º", "2º" }));
        Cano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanoActionPerformed(evt);
            }
        });
        jPanel1.add(Cano, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 187, 66, -1));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 396, -1, -1));

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 396, -1, -1));

        jmasculino.setText("M");
        jmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(jmasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 121, -1, -1));

        Jfeminino.setText("F");
        jPanel1.add(Jfeminino, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 121, -1, -1));

        jLabel6.setText("NIF:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 99, -1, -1));

        Csemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "1º Semestre", "2º Semestre" }));
        Csemestre.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                CsemestreAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Csemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CsemestreActionPerformed(evt);
            }
        });
        jPanel1.add(Csemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 220, 121, -1));

        jLabel7.setText("Semestre:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 220, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 253, 121, 88));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomeActionPerformed

    private void CanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmasculinoActionPerformed

    private void CsemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CsemestreActionPerformed
          /*
        jCsemestre.addActionListener(new ActionListener() {
    private ArrayList<String> disciplinasSelecionadas;

    public void actionPerformed(ActionEvent evt) {
        String semestreSelecionado = (String) jCsemestre.getSelectedItem();
       
        // Simulação de busca das disciplinas para o semestre selecionado
        disciplinasSelecionadas = new ArrayList<>();
        System.out.println("Aqui executou");
        if (semestreSelecionado.equalsIgnoreCase("1º Semestre")) {
            disciplinasSelecionadas.add("Matemática");
            disciplinasSelecionadas.add("Programação");
        } else if (semestreSelecionado.equals("2º Semestre")) {
            disciplinasSelecionadas.add("Física");
            disciplinasSelecionadas.add("História");
        }

        // Preencher a tabela com as disciplinas do semestre selecionado
        DefaultTableModel modeloTabela = (DefaultTableModel) Tabela.getModel();
        modeloTabela.setRowCount(0); // Limpar tabela

        for (String disciplina : disciplinasSelecionadas) {
            modeloTabela.addRow(new Object[]{disciplina});
        }
    }
});
        */
    }//GEN-LAST:event_CsemestreActionPerformed

    private void CsemestreAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_CsemestreAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_CsemestreAncestorAdded

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            try{
            BufferedWriter conexao;
            int matricula;
            String nome,nif,genero = null,data,ano,semestre;
         
        nome=txtnome.getText().toString().trim();
        nif=txtnif.getText();
        ano=Cano.getSelectedItem().toString().trim();
        semestre=Csemestre.getSelectedItem().toString().trim();
        if(Jfeminino.isSelected()){
        genero="Feminino";
        
        }else if(jmasculino.isSelected()){
        genero="Masculino";//jmasculino.getText().trim();
        }
        //Date date=Jdata.getDate();
        SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
     //   Date dataCad=new Date();
     //   data=ft.format(date);
        //data=ft.format(Datacad);
        //data=Jdata.toString();// getDate().toString();
        //privilegio=jprivilegio.getSelectedItem().toString().trim();
        //palavrapw=txtpw.getText();
        //confirmarpw=txtconfpw.getText();
         
          //username=txtnusuario.getText();
         if(nif == null || nome == null ||  "Nenhum".equals(ano) || "Nenhum".equals(semestre) ){
            JOptionPane.showMessageDialog(rootPane,"Todos os campos devem ser preenchidos ou selecionados");
          } else {
              
              
              conexao=new BufferedWriter(new FileWriter("CadastroAlunos.txt", true));
             // ccf.salvardados(conexao,mc);
             conexao.write(nome+";"+nif+";"+genero+";"+";"+ano+";"+semestre+";\n");
             JOptionPane.showMessageDialog(rootPane,"Dados salvos com sucesso");
              conexao.close();
             
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu um ERRO");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cano;
    private javax.swing.JComboBox<String> Csemestre;
    private javax.swing.JRadioButton Jfeminino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jmasculino;
    private javax.swing.JTextField txtnif;
    private javax.swing.JTextField txtnome;
    // End of variables declaration//GEN-END:variables
}
